apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-backend

spec:
  replicas: 3

  selector:
    matchLabels:
      app: python-backend

  template:

    metadata:
      labels:
        app: python-backend

    spec:

      containers:
      - name: python-backend

        image: 091trippe/python-backend:1.0.0

        ports:
        - containerPort: 5000
